'use strict'
const assert = require('node:assert')
const fs = require('node:fs')
const path = require('node:path')
const packageJson = JSON.parse(fs.readFileSync(path.join(__dirname, '..', 'package.json'), 'utf8'))
assert.strictEqual(packageJson.dependencies['bedrock-protocol'], '3.57.0')
assert.ok(Number(process.versions.node.split('.')[0]) >= 22)
const bedrockRoot = path.dirname(require.resolve('bedrock-protocol/package.json'))
const loginVerify = fs.readFileSync(path.join(bedrockRoot, 'src/handshake/loginVerify.js'), 'utf8')
assert.ok(loginVerify.includes('OIDC_JWKS_URL'))
assert.ok(loginVerify.includes('audience: OIDC_AUDIENCE'))
const relaySource = fs.readFileSync(path.join(bedrockRoot, 'src/relay.js'), 'utf8')
assert.ok(relaySource.includes('this.sendBuffer(packet) // Ninj-OS lossless downstream queue'))
assert.ok(relaySource.includes('this.upstream.sendBuffer(e) // Ninj-OS lossless upstream queue'))
assert.ok(relaySource.includes('else this.upstream.sendBuffer(packet)'))
assert.ok(relaySource.includes('if (des.ninjosReencode) this.upstream.queue'))
assert.ok(relaySource.includes('A schema lag must not break gameplay.'))
assert.ok(relaySource.includes('schema lag remains non-disruptive.'))
const minecraftRoot = path.dirname(require.resolve('minecraft-data/package.json'))
const protocol = JSON.parse(fs.readFileSync(path.join(minecraftRoot, 'minecraft-data/data/bedrock/1.26.30/protocol.json'), 'utf8'))
assert.strictEqual(protocol.types.VoxelShape[1].find((field) => field.name === 'cells').type, 'VoxelCells')
const raknetRoot = path.dirname(require.resolve('raknet-native/package.json'))
assert.ok(fs.readFileSync(path.join(raknetRoot, 'binding.js'), 'utf8').includes('helper.getFallbackPath()'))
console.log('session-core package metadata validated')
